// lib/quizData.js

export async function fetchQuizData() {
  return [
    {
      id: 1,
      uniqueId: 1.1,
      text: "What is the capital of France?",
      options: ["Paris", "London", "Rome", "Berlin"],
      answer: "Paris",
    },
    {
      id: 2,
      uniqueId: 2.1,
      text: "Which language is spoken in Brazil?",
      options: ["Spanish", "Portuguese", "French", "English"],
      answer: "Portuguese",
    },
    {
      id: 3,
      uniqueId: 3.1,
      text: "What is 2 + 2?",
      options: ["3", "4", "5", "6"],
      answer: "4",
    },
    {
      id: 4,
      uniqueId: 4.1,
      text: "Which planet is known as the Red Planet?",
      options: ["Earth", "Mars", "Jupiter", "Venus"],
      answer: "Mars",
    },
    {
      id: 5,
      uniqueId: 5.1,
      text: "What is the largest ocean on Earth?",
      options: ["Atlantic", "Indian", "Arctic", "Pacific"],
      answer: "Pacific",
    },
    {
      id: 6,
      uniqueId: 6.1,
      text: "Who invented the telephone?",
      options: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Albert Einstein"],
      answer: "Alexander Graham Bell",
    },
    {
      id: 7,
      uniqueId: 7.1,
      text: "Which country is known as the Land of the Rising Sun?",
      options: ["China", "Japan", "South Korea", "Thailand"],
      answer: "Japan",
    },
    {
      id: 8,
      uniqueId: 8.1,
      text: "What is the smallest continent by land area?",
      options: ["Asia", "Australia", "Africa", "Europe"],
      answer: "Australia",
    },
    {
      id: 9,
      uniqueId: 9.1,
      text: "Which element has the chemical symbol 'O'?",
      options: ["Oxygen", "Osmium", "Ozone", "Oganesson"],
      answer: "Oxygen",
    },
    {
      id: 10,
      uniqueId: 10.1,
      text: "How many continents are there on Earth?",
      options: ["6", "7", "8", "5"],
      answer: "7",
    },
    {
      id: 11,
      uniqueId: 11.1,
      text: "What is the hardest natural substance on Earth?",
      options: ["Gold", "Iron", "Diamond", "Platinum"],
      answer: "Diamond",
    },
    {
      id: 12,
      uniqueId: 12.1,
      text: "Which is the longest river in the world?",
      options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
      answer: "Nile",
    },
    {
      id: 13,
      uniqueId: 13.1,
      text: "Who painted the Mona Lisa?",
      options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"],
      answer: "Leonardo da Vinci",
    },
    {
      id: 14,
      uniqueId: 14.1,
      text: "What is the freezing point of water in Celsius?",
      options: ["0", "32", "100", "-1"],
      answer: "0",
    },
    {
      id: 15,
      uniqueId: 15.1,
      text: "Which animal is known as the King of the Jungle?",
      options: ["Elephant", "Lion", "Tiger", "Giraffe"],
      answer: "Lion",
    },
  ];
}
